part b init

diff --git a/grade_utils b/grade_utils
--- a/grade_utils
+++ b/grade_utils
@@ -1,42 +1,81 @@
 #!/bin/bash
+# Utilities for making grade-scripts shorter
 
-source grade_utils
-TIMEOUT=20
-run_in_folder_if_exists "$1"
+set -o pipefail   # see https://unix.stackexchange.com/a/267031/16569
+exec 2>&1         # redirect stderr to stdout: https://unix.stackexchange.com/q/505581/16569
 
-printf "\n\n### Cleaning old files ###\n"
-make -f Makefile clean
+TIMEOUT=10  # 10 seconds - default timeout
 
-total=0
-i=0
+typeset -F SECONDS
+SECONDS=0
+echo "--- $SECONDS seconds"
 
-let "i=i+1"
-printf "\n\n### Check $i: our demo program should compile with your class\n"
-grade_command make -j8 -f Makefile demo 
-printf "### Score $i: $grade\n"
-total=$((total + grade))
+run_in_folder_if_exists() {
+	if [ -d "$1" ]
+	then
+		GRADEFILES=`ls -p | grep -v /`
+		cp $GRADEFILES $1/
+		call cd $1
+		source $0
+		rm $GRADEFILES
+		cd ..
+		exit 0
+	fi
+}
 
-let "i=i+1"
-printf "\n\n### Check $i: our demo program should run without errors\n"
-grade_command ./demo
-printf "### Score $i: $grade\n"
-total=$((total + grade))
 
-let "i=i+1"
-printf "\n\n### Check $i: your test should compile \n"
-grade_command make -j8 -f Makefile test 
-printf "### Score $i: $grade\n"
-total=$((total + grade))
+# A function that echoes and executes a command.
+call() { 
+	echo "! ${@/eval/}" 
+	$@
+}
 
-let "i=i+1"
-printf "\n\n### Check $i: you should write some new tests\n"
-grade_command ./test
-printf "### Score $i: $grade\n"
-total=$((total + grade))
+# A function that echoes and executes a command.
+# If it fails, it sets grade=0.
+# If it succeeds, it sets grade=100.
+grade_command() { 
+	grade=100
+	call timeout $TIMEOUT $@
+	exitcode=$?
+	if [ $exitcode -ne 0 ]
+	then 
+		printf "*** Command failed. Exit code: $exitcode ***\n"
+		grade=0
+	fi
+	echo "--- $SECONDS seconds"
+}
 
-total=$((total / i))
-printf "\n\nGrade: $total\n\n"
+# A function that echoes and executes a command.
+# If it fails, it sets grade=0.
+# If it succeeds, it sets grade=[last line of output]
+grade_program() { 
+	program=$1
+	echo "! timeout $TIMEOUT ./$program" 
+	timeout $TIMEOUT ./$program
+	exitcode=$?
+	if [ $exitcode -ne 0 ]
+	then 
+		printf "*** Program failed. Exit code: $exitcode ***\n"
+		grade=0
+	else
+		grade=$( { timeout $TIMEOUT ./$program || echo 0; } | tail -n1 )
+	fi
+	echo "--- $SECONDS seconds"
+}
 
-make -f Makefile --silent clean
 
-exit $total
+
+# from here: https://stackoverflow.com/a/1115909/827927
+swap() {
+    local TMPFILE=tmp.$$
+	if [ -f $1 ] && [ -f $2 ]
+	then
+    	mv $1 $TMPFILE && mv $2 $1 && mv $TMPFILE $2
+	elif [ -f $1 ]
+	then
+    	mv $1 $2
+	elif [ -f $2 ]
+	then
+    	mv $2 $1
+	fi
+}
